name: TImingLeague
version: '1.0-SNAPSHOT'
main: com.tekad.TimingLeague.TImingLeague
api-version: '1.20'
depend: [TimingSystem]
softdepend: [DecentHolograms]
commands:
  league:
    description: Main league command
    usage: /league
    aliases: []
    permission: league.use
    permission-message: You do not have permission to use this command.
    tab-completer: com.tekad.TimingLeague.commands.LeagueCommandCompleter

